### ISSUE TITLE
Implement QR Code reader

### ISSUE THREAD

**Issue by hallmayer** [iotwahlfach/EdgeDevice#4]
Implement a python application which reads qr codes from camera

**Comment by hallmayer** [comment]
Relevated Links:
https://www.hackster.io/achraf-oukheir/qr-code-reader-decoder-mac-raspberry-pi-7deb99
https://www.pyimagesearch.com/2018/05/21/an-opencv-barcode-and-qr-code-scanner-with-zbar/

**Comment by xmichaelw** [comment]
https://www.pyimagesearch.com/2018/09/19/pip-install-opencv/
https://stackoverflow.com/questions/48965309/h5py-import-error-on-libhdf5-serial-so-100

**Comment by xmichaelw** [comment]
should be finished as soon as the picamera is enabled on the second (111) Raspi
